[Unit]
After=network-online.target
Wants=network-online.target

[Service]
Environment="OLLAMA_HOST=192.0.2.150:11434"
Environment="OLLAMA_KEEP_ALIVE=-1"
Environment="OLLAMA_ORIGINS=*"
Restart=on-failure
RestartSec=5
